let initializeApp, getDatabase, ref, onValue, set, update, push, get, runTransaction;
let getAuth, signInAnonymously, signInWithEmailAndPassword, onAuthStateChanged, signOut;

const COLORS = [
  ["레몬 노랑","#FFE96B"],["해바라기 노랑","#FFD05A"],["귤 주황","#FFB05C"],["복숭아 주황","#FF9671"],["딸기 빨강","#FF7777"],["장미 분홍","#FF98BD"],["포도 보라","#C6A3FF"],["라일락 보라","#D9C8FF"],["바다 파랑","#8BD7F4"],["하늘 파랑","#B8E7FF"],["청록","#80DED2"],["숲 초록","#9FD98D"],["연두","#D6EC91"],["라임","#C9F17D"],["라떼 갈색","#D9B18D"],["모래 베이지","#F1D39A"],["구름 회색","#D2D5DE"],["살구 크림","#FFD6A3"],["민트 아이스","#B7EEE5"],["블루베리","#94A8FF"],["코랄 핑크","#FFB0A4"]
].map(([name,hex],id)=>({id,name,hex}));
const COLOR_OPTIONS = [
  ...COLORS,
  ...Array.from({length:79},(_,index)=>{
    const id=COLORS.length+index;
    return {id,name:`담벼락 색 ${id+1}`,hex:`hsl(${(id*47)%360} 78% 78%)`};
  })
];
const ROOM_ID = new URLSearchParams(location.search).get("room")?.trim();
const TEACHER_UID = "Z6WEsEFSTBbq6eeIF3E0RaBGoQZ2";
const MAX_POSTS=3, MAX_LENGTH=80, MAX_QUESTIONS=5;
const appEl=document.querySelector("#app");
let db, auth, room={}, teacherRecords={}, my={};
let selectedColor=null, teacher=false, selectedPost=null;
let demoScene="wall";
let demoColorId=2, demoQuestionCount=2, demoShowAttendance=false, demoPresentPost="c";
let demoJoinCode="";

function esc(s=""){return String(s).replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}
function sessionKey(){return `summer-colors-${ROOM_ID}`;}
function saveSession(v){localStorage.setItem(sessionKey(),JSON.stringify(v));}
function loadSession(){try{return JSON.parse(localStorage.getItem(sessionKey())||"{}")}catch{return{}}}
function color(id){return COLOR_OPTIONS.find(c=>c.id===id) || COLOR_OPTIONS[0];}
function postEntries(){return Object.entries(room.posts||{}).map(([id,v])=>({id,...v}));}
function questionCount(post){return Object.keys(post.questions||{}).length;}
function phase(){return room.phase||"join";}
function shell(content){appEl.innerHTML=`<div class="shell"><header class="brand"><div class="brand-mark" aria-hidden="true"></div><div><h1>스티커 담벼락</h1><span class="muted">생각을 붙이고, 궁금한 이야기에 질문을 남겨요.</span></div></header>${content}</div>`;}
function makeRoomId(){return `STICKER-${crypto.getRandomValues(new Uint32Array(1))[0].toString(36).toUpperCase().slice(0,6)}`;}
function roomUrl(id){return `${location.pathname}?room=${encodeURIComponent(id)}`;}

async function boot(){
  try {
    const {firebaseConfig}=await import("./firebase-config.js");
    if(!firebaseConfig?.apiKey) throw new Error("config");
    ({initializeApp}=await import("https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js"));
    ({getDatabase,ref,onValue,set,update,push,get,runTransaction}=await import("https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js"));
    ({getAuth,signInAnonymously,signInWithEmailAndPassword,onAuthStateChanged,signOut}=await import("https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js"));
    const fb=initializeApp(firebaseConfig); db=getDatabase(fb); auth=getAuth(fb);
    if(ROOM_ID) onValue(ref(db,`rooms/${ROOM_ID}`),snap=>{room=snap.val()||{}; render();});
    onAuthStateChanged(auth,user=>{
      if(!user) { signInAnonymously(auth); return; }
      teacher=user.uid===TEACHER_UID;
      if(!teacher) my={...loadSession(),uid:user.uid};
      if(teacher && ROOM_ID) onValue(ref(db,`teacherRecords/${ROOM_ID}/participants`),snap=>{teacherRecords=snap.val()||{};render();});
      render();
    });
    my=loadSession(); render();
  } catch { renderConfig(); }
}
function renderRoomRequired(){
 shell(`<section class="wall-hero"><div class="wall-copy"><div class="step">우리 반 생각 모으기</div><h2>오늘의 생각으로<br>담벼락을 채워 볼까요?</h2><p>선생님은 새 담벼락을 만들고, 학생은 참여코드로 들어와요.</p><div class="actions"><button class="btn" id="open-teacher-login">교사로 담벼락 만들기</button></div></div><div class="wall-board" aria-label="포스트잇 담벼락"><div class="pin"></div><div class="wall-sticky s1">오늘 기대되는 것<br>한 가지! ✨</div><div class="wall-sticky s2">내가 소개하고 싶은<br>이야기 🌻</div><div class="wall-sticky s3">궁금한 친구의 글에는<br>❔ 질문 남기기</div><div class="wall-sticky s4">생각은 달라도<br>괜찮아요</div></div></section><section class="card join-card"><div class="step">학생 입장</div><h2>참여코드를 입력해 주세요</h2><p>선생님이 칠판이나 화면에 보여 준 참여코드로 들어와요.</p><div class="fields"><label>참여코드 <input id="room-code" maxlength="20" placeholder="예: STICKER-ABC123" autocomplete="off"></label></div><div id="room-code-message"></div><div class="actions"><button class="btn" id="enter-room">담벼락 들어가기</button></div></section>`);
 document.querySelector('#open-teacher-login').onclick=renderLogin;
 document.querySelector('#enter-room').onclick=enterRoom;
}
async function enterRoom(){const code=document.querySelector('#room-code').value.trim().toUpperCase();const msg=document.querySelector('#room-code-message');if(!/^STICKER-[A-Z0-9]{4,10}$/.test(code)) return msg.innerHTML='<p class="error">참여코드 형식을 확인해 주세요.</p>';try{const snap=await get(ref(db,`rooms/${code}`));if(!snap.exists()) return msg.innerHTML='<p class="error">열린 담벼락을 찾지 못했어요. 코드를 다시 확인해 주세요.</p>';location.assign(roomUrl(code));}catch{msg.innerHTML='<p class="error">잠시 후 다시 시도해 주세요.</p>';}}
function renderConfig(){renderDemo();}
function renderDemo(){
  const mock=[
    {id:"a",authorColorId:8,text:"할머니 댁 근처 바다에서 조개를 주웠어요. 물이 정말 차가웠어요! 🐚",questions:{q1:{text:"조개는 몇 개나 주웠어요?"},q2:{text:"바다에는 언제 갔어요?"}}},
    {id:"b",authorColorId:3,text:"방학 동안 자전거 타는 법을 더 잘하게 되었어요. 넘어지지 않고 긴 길도 갔어요! 🚲",questions:{q1:{text:"가장 멀리 어디까지 갔어요?"}}},
    {id:"c",authorColorId:15,text:"집에서 수박 화채를 만들었어요. 내가 고른 과일을 많이 넣었어요. 🍉",questions:{q1:{text:"어떤 과일을 넣었어요?"},q2:{text:"다음에도 만들고 싶어요?"},q3:{text:"가장 맛있었던 과일은 무엇이에요?"}}}
  ];
  const nav=`<nav class="demo-nav" aria-label="장면 선택"><button data-demo="wall" class="${demoScene==='wall'?'active':''}">1. 담벼락 만들기</button><button data-demo="code" class="${demoScene==='code'?'active':''}">2. 참여코드</button><button data-demo="join" class="${demoScene==='join'?'active':''}">3. 색 고르기</button><button data-demo="write" class="${demoScene==='write'?'active':''}">4. 포스트잇 쓰기</button><button data-demo="vote" class="${demoScene==='vote'?'active':''}">5. 질문 시간</button><button data-demo="present" class="${demoScene==='present'?'active':''}">6. 교사 발표</button></nav>`;
  let content="";
  if(demoScene==='wall') content=`<section class="wall-hero"><div class="wall-copy"><div class="step">우리 반 생각 모으기</div><h2>오늘의 생각으로<br>담벼락을 채워 볼까요?</h2><p>교사가 담벼락을 열고, 학생은 참여코드를 입력해 들어와요.</p><div class="actions"><button class="btn" data-demo="host">교사로 담벼락 만들기</button><button class="btn secondary" data-demo="code">학생으로 참여하기</button></div></div><div class="wall-board" aria-label="포스트잇 담벼락 예시"><div class="pin"></div><div class="wall-sticky s1">오늘 기대되는 것<br>한 가지! ✨</div><div class="wall-sticky s2">내가 소개하고 싶은<br>이야기 🌻</div><div class="wall-sticky s3">궁금한 친구의 글에는<br>❔ 질문 남기기</div><div class="wall-sticky s4">생각은 달라도<br>괜찮아요</div></div></section><section class="board-guide"><div><strong>교사가 열기</strong><span>담벼락마다 참여코드가 만들어집니다.</span></div><div><strong>코드로 참여</strong><span>학생은 열린 담벼락에만 들어옵니다.</span></div><div><strong>함께 이야기</strong><span>교사가 질문과 발표 순서를 조절합니다.</span></div></section>`;
  if(demoScene==='host') content=`<section class="card"><div class="step">교사 화면 · 담벼락 만들기</div><h2>새 담벼락을 열었어요</h2><p>학생에게 아래 참여코드를 보여 주거나, QR 코드로 안내하세요.</p><div class="join-code"><span>참여코드</span><strong>STICKER-42</strong><button class="btn secondary" id="copy-code">코드 복사</button></div><div class="notice"><strong>담벼락 제목</strong><br>우리 반의 오늘 생각</div><div class="actions"><button class="btn" data-demo="present">교사 담벼락 열기</button><button class="btn secondary" data-demo="wall">처음으로</button></div></section>`;
  if(demoScene==='code') content=`<section class="card join-card"><div class="step">학생 화면 · 참여코드</div><h2>참여코드를 입력해 주세요</h2><p>선생님이 알려 준 코드가 있어야 담벼락에 들어갈 수 있어요.</p><div class="fields"><label>참여코드 <input id="demo-code" maxlength="12" placeholder="예: STICKER-42" value="${esc(demoJoinCode)}" autocomplete="off"></label></div><div id="code-message"></div><div class="actions"><button class="btn" id="enter-code">담벼락 들어가기</button><button class="btn secondary" data-demo="wall">돌아가기</button></div></section>`;
  if(demoScene==='join') content=`<section class="card"><div class="step">학생 화면 · 입장</div><h2>나만의 담벼락 색을 골라요</h2><p>출석 번호는 선생님만 확인할 수 있어요. 친구에게는 색 이름도 보이지 않습니다.</p><div class="fields"><label>출석 번호 <input value="7" readonly aria-label="출석 번호 예시"></label></div><div class="color-grid">${COLOR_OPTIONS.slice(0,20).map((c,i)=>`<button class="color-card" data-demo-color="${c.id}" style="background:${c.hex}" ${c.id===demoColorId?'aria-pressed="true"':''} ${i===5?'disabled':''}><span class="color-no">색 ${c.id+1}</span><strong>${c.name}</strong>${i===5?'<small>선택됨</small>':''}</button>`).join('')}</div><div class="actions"><button class="btn" data-demo="write">${color(demoColorId).name}으로 시작하기</button></div></section>`;
  if(demoScene==='write') {const c=color(demoColorId);content=`<section class="card"><div class="topbar"><div><div class="step">학생 화면 · 생각 붙이기</div><h2>${c.name}의 포스트잇</h2></div><span class="count">1 / 3장</span></div><div class="composer"><label>오늘 담벼락에 붙이고 싶은 생각<textarea id="demo-text" maxlength="80">수영장에서 물놀이를 했어요! 🏊</textarea></label><span class="muted">최대 80자 · 이모지 사용 가능</span><div class="actions"><button class="btn" id="demo-add">포스트잇 붙이기</button><button class="btn secondary" data-demo="vote">친구들 담벼락 보기</button></div></div><div class="stickies" id="demo-my-sticky"><article class="sticky" style="background:${c.hex}"><p>수영장에서 물놀이를 했어요! 🏊</p><div class="sticky-meta">내 포스트잇</div></article></div></section>`}
  if(demoScene==='vote') content=`<section class="card"><div class="topbar"><div><div class="step">학생 화면 · 질문</div><h2>궁금한 이야기에 질문을 남겨요</h2></div><span class="count">${demoQuestionCount} / 5개 질문</span></div><p class="notice">모든 포스트잇은 같은 색으로 보입니다. 글과 질문 내용만 보고 궁금한 이야기를 골라요.</p><div class="stickies">${mock.map(p=>demoSticky(p,false)).join('')}</div></section>`;
  if(demoScene==='present') content=`<section class="card"><div class="topbar"><div><div class="step">교사 화면 · 발표</div><h2>질문이 많은 순서로 이야기 들어요</h2></div><span class="count">투표 정지</span></div><div class="control-grid"><aside class="controls teacher-only"><strong>교사 제어</strong><button class="btn secondary" id="demo-attendance">출석 번호 ${demoShowAttendance?'숨기기':'보이기'}</button><button class="btn secondary">기록 내려받기</button><p class="muted">포스트잇을 선택하면 그 글만 원래 색으로 나타납니다.</p></aside><section><div class="stickies">${mock.sort((a,b)=>Object.keys(b.questions).length-Object.keys(a.questions).length).map(p=>demoSticky(p,p.id===demoPresentPost)).join('')}</div></section></div></section>`;
  shell(`<div class="preview-label">Firebase 연결 전 화면 미리보기</div>${nav}${content}`);
  document.querySelectorAll('[data-demo]').forEach(b=>b.onclick=()=>{demoScene=b.dataset.demo;renderDemo();});
  document.querySelectorAll('[data-demo-color]').forEach(b=>b.onclick=()=>{demoColorId=Number(b.dataset.demoColor);renderDemo();});
  document.querySelector('#demo-add')?.addEventListener('click',()=>{const text=document.querySelector('#demo-text').value.trim();if(!text)return;document.querySelector('#demo-my-sticky').insertAdjacentHTML('afterbegin',`<article class="sticky" style="background:${color(demoColorId).hex}"><p>${esc(text)}</p><div class="sticky-meta">방금 붙인 포스트잇</div></article>`);});
  document.querySelectorAll('[data-demo-question]').forEach(form=>form.onsubmit=e=>{e.preventDefault();const input=form.querySelector('input');if(!input.value.trim()||demoQuestionCount>=5)return;demoQuestionCount+=1;form.closest('.sticky').querySelector('.question-list').insertAdjacentHTML('beforeend',`<li>${esc(input.value.trim())}</li>`);input.value='';form.querySelector('button').disabled=demoQuestionCount>=5;document.querySelector('.count').textContent=`${demoQuestionCount} / 5개 질문`;});
  document.querySelector('#demo-attendance')?.addEventListener('click',()=>{demoShowAttendance=!demoShowAttendance;renderDemo();});
  document.querySelectorAll('[data-demo-post]').forEach(b=>b.onclick=()=>{demoPresentPost=b.dataset.demoPost;renderDemo();});
  document.querySelector('#copy-code')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText('STICKER-42');document.querySelector('#copy-code').textContent='복사됨!';}catch{document.querySelector('#copy-code').textContent='STICKER-42'}});
  document.querySelector('#enter-code')?.addEventListener('click',()=>{const value=document.querySelector('#demo-code').value.trim().toUpperCase();demoJoinCode=value;if(value==='STICKER-42'){demoScene='join';renderDemo();}else{document.querySelector('#code-message').innerHTML='<p class="error">참여코드를 다시 확인해 주세요.</p>'}});
}
function demoSticky(p,reveal){const c=color(p.authorColorId);const qs=Object.values(p.questions||{});return `<article class="sticky public ${reveal?'selected-post':''}" style="background:${reveal?c.hex:'#fff7a5'}"><p>${esc(p.text)}</p><div class="sticky-meta">❔ 질문 ${qs.length}개${reveal?` · ${c.name}${demoShowAttendance?' · 출석 7번':''}`:''}</div><ul class="question-list">${qs.map(q=>`<li>${esc(q.text)}</li>`).join('')}</ul>${demoScene==='vote'?`<form class="question-form" data-demo-question="${p.id}"><input maxlength="80" placeholder="궁금한 점을 적어요" aria-label="질문 내용"><button class="btn" ${demoQuestionCount>=5?'disabled':''}>질문</button></form>`:demoScene==='present'?`<div class="actions"><button class="btn secondary" data-demo-post="${p.id}">이 포스트잇 발표하기</button></div>`:''}</article>`}
function render(){if(!db)return; if(!ROOM_ID) return teacher?renderTeacherLobby():renderRoomRequired(); if(teacher) return renderTeacher(); if(!my.colorId)return renderJoin(); return renderStudent();}
function renderTeacherLobby(){shell(`<section class="card"><div class="topbar"><div><div class="step">교사 전용</div><h2>새 담벼락 만들기</h2></div><button class="btn secondary" id="logout">로그아웃</button></div><p>활동마다 새 참여코드가 만들어집니다. 학생에게 이 코드 또는 링크만 안내해 주세요.</p><div class="fields"><label>담벼락 제목 <input id="new-room-title" maxlength="40" value="우리 반의 오늘 생각" placeholder="예: 우리 반 여름의 색"></label></div><div id="create-room-message"></div><div class="actions"><button class="btn" id="create-room">새 담벼락 열기</button></div></section>`);document.querySelector('#logout').onclick=()=>signOut(auth);document.querySelector('#create-room').onclick=createRoom;}
async function createRoom(){const title=document.querySelector('#new-room-title').value.trim()||'우리 반의 오늘 생각';const msg=document.querySelector('#create-room-message');const id=makeRoomId();try{await set(ref(db,`rooms/${id}`),{title,phase:'join',showAttendance:false,createdAt:Date.now(),createdBy:TEACHER_UID});location.assign(roomUrl(id));}catch{msg.innerHTML='<p class="error">담벼락을 만들지 못했어요. Firebase 규칙이 게시되었는지 확인해 주세요.</p>';}}
function renderJoin(){ const taken=new Set(Object.keys(room.colorLocks||{}).map(Number)); shell(`<section class="card"><div class="step">1 / 2 입장하기</div><h2>나만의 담벼락 색을 골라요</h2><p>출석 번호는 선생님만 확인할 수 있어요. 친구들에게는 색 이름도 보이지 않습니다.</p><div class="fields"><label>출석 번호 <input id="attendance" inputmode="numeric" maxlength="2" placeholder="예: 7" aria-describedby="attendance-note"></label><span id="attendance-note" class="muted">숫자만 입력해 주세요.</span></div><h3>색 닉네임 선택</h3><div class="color-grid">${COLOR_OPTIONS.map(c=>`<button class="color-card" data-color="${c.id}" style="background:${c.hex}" ${taken.has(c.id)?"disabled":""} aria-pressed="${selectedColor===c.id}"><span class="color-no">색 ${c.id+1}</span><strong>${c.name}</strong>${taken.has(c.id)?"<small>선택됨</small>":""}</button>`).join("")}</div><div id="join-message"></div><div class="actions"><button class="btn" id="join" ${selectedColor===null||!my.uid?"disabled":""}>이 색으로 시작하기</button><button class="btn secondary" id="teacher-login">교사 로그인</button></div></section>`);
 document.querySelectorAll("[data-color]").forEach(b=>b.onclick=()=>{selectedColor=Number(b.dataset.color);renderJoin();});
 document.querySelector("#join").onclick=join;
 document.querySelector("#teacher-login").onclick=renderLogin;
}
async function join(){const attendance=document.querySelector("#attendance").value.trim(); const msg=document.querySelector("#join-message"); if(!/^\d{1,2}$/.test(attendance)) return msg.innerHTML='<p class="error">출석 번호를 숫자로 입력해 주세요.</p>';
 const lock=ref(db,`rooms/${ROOM_ID}/colorLocks/${selectedColor}`); const result=await runTransaction(lock,current=>current||my.uid); if(!result.committed||result.snapshot.val()!==my.uid){msg.innerHTML='<p class="error">방금 다른 친구가 이 색을 골랐어요. 다른 색을 골라 주세요.</p>';return;}
 const data={...my,colorId:selectedColor,attendance,questionIds:{}}; await set(ref(db,`teacherRecords/${ROOM_ID}/participants/${my.uid}`),{colorId:selectedColor,attendance,joinedAt:Date.now()}); saveSession(data);my=data;render();}
function renderStudent(){const c=color(my.colorId); const isVoting=phase()==="voting", isPresenting=phase()==="presenting"; const posts=postEntries(); shell(`<section class="card"><div class="topbar"><div><div class="step">${isVoting?"질문 시간":isPresenting?"발표 시간":"2 / 2 포스트잇 쓰기"}</div><h2>${isVoting?"궁금한 이야기에 질문을 남겨요":isPresenting?"친구의 이야기를 들어요":`${c.name}의 포스트잇`}</h2></div><span class="count">${posts.filter(p=>p.authorId===my.uid).length} / ${MAX_POSTS}장</span></div>${phase()==="writing"?`<div class="composer"><label>${esc(room.title||'오늘 담벼락에 붙이고 싶은 생각')}<textarea id="post-text" maxlength="${MAX_LENGTH}" placeholder="말하고 싶은 만큼만 적어도 괜찮아요."></textarea></label><span class="muted">최대 ${MAX_LENGTH}자 · 이모지 사용 가능</span><div class="actions"><button class="btn" id="add-post">포스트잇 붙이기</button></div></div><p class="notice">친구의 이야기는 평가하거나 놀리지 않고, 궁금한 점을 따뜻하게 물어봐요.</p>`:isVoting?`<p class="notice">질문은 총 ${MAX_QUESTIONS}개까지 남길 수 있어요. 포스트잇을 쓴 친구의 색은 아직 보이지 않아요.</p>`:`<p class="notice">선생님이 고른 포스트잇의 색이 나타나면, 해당 친구의 이야기를 함께 들어요.</p>`}<div class="stickies">${posts.map(p=>studentSticky(p,isVoting,isPresenting,c)).join("")||'<p class="muted">아직 붙은 포스트잇이 없어요.</p>'}</div></section>`);
 if(phase()==="writing"){document.querySelector("#add-post").onclick=addPost;} if(isVoting) bindQuestions(); }
function studentSticky(p,isVoting,isPresenting,c){const mine=p.authorId===my.uid; const revealed=isPresenting&&room.selectedPostId===p.id; const bg=revealed?color(p.authorColorId).hex:isVoting||isPresenting?"#fff7a5":mine?c.hex:"#fff7a5"; const qs=Object.values(p.questions||{}); return `<article class="sticky ${(isVoting||isPresenting)?"public":""} ${revealed?"selected-post":""}" style="background:${bg}"><p>${esc(p.text)}</p><div class="sticky-meta">${(isVoting||isPresenting)?`❔ 질문 ${qs.length}개${revealed?` · ${esc(color(p.authorColorId).name)}`:""}`:mine?"내 포스트잇":""}</div>${isVoting?`<ul class="question-list">${qs.map(q=>`<li>${esc(q.text)}</li>`).join("")}</ul><form class="question-form" data-post="${p.id}"><input maxlength="${MAX_LENGTH}" placeholder="궁금한 점을 적어요" aria-label="질문 내용"><button class="btn" ${Object.keys(my.questionIds||{}).length>=MAX_QUESTIONS||my.questionIds?.[p.id]?"disabled":""}>질문</button></form>`:isPresenting?`<ul class="question-list">${qs.map(q=>`<li>${esc(q.text)}</li>`).join("")}</ul>`:""}</article>`;}
async function addPost(){const text=document.querySelector("#post-text").value.trim();if(!text)return; if(postEntries().filter(p=>p.authorId===my.uid).length>=MAX_POSTS)return; const id=push(ref(db,`rooms/${ROOM_ID}/posts`)).key; await set(ref(db,`rooms/${ROOM_ID}/posts/${id}`),{authorId:my.uid,authorColorId:my.colorId,text,createdAt:Date.now()});}
function bindQuestions(){document.querySelectorAll(".question-form").forEach(form=>form.onsubmit=async e=>{e.preventDefault();const postId=form.dataset.post,text=form.querySelector("input").value.trim();if(!text||my.questionIds?.[postId]||Object.keys(my.questionIds||{}).length>=MAX_QUESTIONS)return; const id=push(ref(db,`rooms/${ROOM_ID}/posts/${postId}/questions`)).key; await set(ref(db,`rooms/${ROOM_ID}/posts/${postId}/questions/${id}`),{text,createdAt:Date.now()}); my.questionIds={...(my.questionIds||{}),[postId]:id};saveSession(my);render();});}
function renderLogin(){shell(`<section class="card"><div class="step">교사 전용</div><h2>교사 로그인</h2><div class="fields"><label>이메일 <input id="email" type="email"></label><label>비밀번호 <input id="password" type="password"></label></div><div id="login-error"></div><div class="actions"><button class="btn" id="login">로그인</button><button class="btn secondary" id="back">돌아가기</button></div></section>`);document.querySelector("#back").onclick=render;document.querySelector("#login").onclick=async()=>{try{await signInWithEmailAndPassword(auth,document.querySelector("#email").value,document.querySelector("#password").value)}catch{document.querySelector("#login-error").innerHTML='<p class="error">로그인 정보를 확인해 주세요.</p>'}}}
function renderTeacher(){const posts=postEntries().sort((a,b)=>questionCount(b)-questionCount(a)||a.createdAt-b.createdAt); selectedPost=posts.find(p=>p.id===room.selectedPostId)||null; shell(`<section class="card"><div class="topbar"><div><div class="step">교사 제어 · ${phaseLabel()}</div><h2>${esc(room.title||'우리 반의 오늘 생각')}</h2></div><button class="btn secondary" id="logout">로그아웃</button></div><div class="join-code"><span>참여코드</span><strong>${esc(ROOM_ID)}</strong><button class="btn secondary" id="copy-room-link">학생 링크 복사</button></div><div class="control-grid"><aside class="controls teacher-only"><strong>진행 제어</strong><button class="btn" data-phase="writing">1. 작성 시작</button><button class="btn" data-phase="voting">2. 전체 공개·질문 시작</button><button class="btn danger" data-phase="presenting">3. 질문 정지·발표 시작</button><button class="btn secondary" id="toggle-attendance">출석 번호 ${room.showAttendance?"숨기기":"보이기"}</button><button class="btn secondary" id="download">기록 내려받기</button><p class="muted">학생과 함께 이 화면을 볼 때는 출석 번호 표시를 기본으로 꺼 두세요.</p><hr><strong>현재 발표자</strong><p>${selectedPost?`${color(selectedPost.authorColorId).name} · 질문 ${questionCount(selectedPost)}개`:"아직 선택하지 않음"}</p></aside><section><div class="legend"><span class="tag">포스트잇 ${posts.length}장</span><span class="tag">참여 ${Object.keys(room.colorLocks||{}).length}명</span>${room.showAttendance?'<span class="tag">출석 번호 표시 중</span>':""}</div><div class="stickies">${posts.map(teacherSticky).join("")||'<p class="muted">아직 포스트잇이 없어요.</p>'}</div></section></div></section>`);document.querySelector("#logout").onclick=()=>signOut(auth);document.querySelectorAll("[data-phase]").forEach(b=>b.onclick=()=>update(ref(db,`rooms/${ROOM_ID}`),{phase:b.dataset.phase}));document.querySelector("#toggle-attendance").onclick=()=>update(ref(db,`rooms/${ROOM_ID}`),{showAttendance:!room.showAttendance});document.querySelector("#download").onclick=download;document.querySelector('#copy-room-link').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);document.querySelector('#copy-room-link').textContent='복사됨!'}catch{document.querySelector('#copy-room-link').textContent=location.href}};document.querySelectorAll("[data-select-post]").forEach(b=>b.onclick=()=>update(ref(db,`rooms/${ROOM_ID}`),{selectedPostId:b.dataset.selectPost,phase:"presenting"}));}
function teacherSticky(p){const active=room.selectedPostId===p.id;const participant=teacherRecords[p.authorId]||{};const c=color(p.authorColorId||0);const reveal=active&&phase()==="presenting";const bg=reveal?c.hex:"#fff7a5";return `<article class="sticky ${active?"selected-post":""}" style="background:${bg}"><p>${esc(p.text)}</p><div class="sticky-meta">❔ 질문 ${questionCount(p)}개 ${reveal?`· ${esc(c.name)}${room.showAttendance?` · 출석 ${esc(participant.attendance||"-")}`:""}`:""}</div><ul class="question-list">${Object.values(p.questions||{}).map(q=>`<li>${esc(q.text)}</li>`).join("")}</ul><div class="actions"><button class="btn secondary" data-select-post="${p.id}">이 포스트잇 발표하기</button></div></article>`;}
function phaseLabel(){return ({join:"입장 대기",writing:"포스트잇 작성",voting:"전체 공개·질문",presenting:"발표 진행"})[phase()]||"입장 대기";}
function download(){const data={exportedAt:new Date().toISOString(),room,teacherRecords};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="우리-반-여름의-색-기록.json";a.click();URL.revokeObjectURL(a.href);}
boot();
